# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default='Hola soy un texto de prueba por defecto'),
            preserve_default=False,
        ),
    ]
