# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20160924_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
    ]
